### ISSUE TITLE
ERROR in [default] - @types/jasmine

### ISSUE THREAD

**Issue by ghost** [codeschool/WatchUsBuild-Angular2Final#3]
When I run 

> ng serve

I the following error:
`ERROR in [default] {project location}/WatchUsBuild-Angular2Final/node_modules/@types/jasmine/index.d.ts:40:37A parameter initializer is only allowed in a function or constructor implementation.`

The error is caused by a later release of @types/jasmine.

Solution is to update the package.json -> `"@types/jasmine": "2.2.30",`

Then run:

> npm install

> ng serve

**Comment by sergiocruz** [comment]
I just upgraded this project to @angular/cli 1.0, so this problem should now be resolved.
